### ISSUE TITLE
Enable dependabot

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/go-square#21]
## Context

https://github.com/celestiaorg/go-square/blob/414d7f7849671d01b7055247a348fdca89b66ca0/go.mod#L3

## Problem

It looks like dependabot isn't enabled on this repo because it uses Go 1.21.5 but Go 1.21.6 has been released

## Acceptance Criteria

Enable dependabot

**Comment by rootulp** [comment]
I'm blocked b/c I don't have permission to see the settings on this repo. 

@MSevey can you please give me admin or maintainer permissions on this repo?

**Comment by rootulp** [comment]
I think you're right b/c celestia-app has dependabot enabled and we've had to manually bump Go versions. But I think it's still a good idea to enable dependabot on this repo to bump the Go deps even though there aren't many.

**Comment by cristaloleg** [comment]
No-no, I'm about another thing which is not dependabot related: what is the reason to bump Go version in `go.mod` at all?

**Comment by rootulp** [comment]
So that we can use features from new Go releases.

**Comment by cristaloleg** [comment]
Fair enough. The only thing why I started this dialogue is that I saw `go.mod` bumps only when they are reaaaally needed. Also, Go patch releases don't give any language changes.

**Comment by MSevey** [comment]
> I'm blocked b/c I don't have permission to see the settings on this repo.
> 
> @MSevey can you please give me admin or maintainer permissions on this repo?

done

**Comment by rootulp** [comment]
Dependabot was already enabled. I confirmed the [config file](https://github.com/celestiaorg/go-square/blob/main/.github/dependabot.yml) looks good.

## Screenshot

![Screenshot 2024-05-29 at 11 05 30 AM](https://github.com/celestiaorg/go-square/assets/3699047/d2e6ca5a-8507-4a40-bc68-540d7c3b71e7)
