### ISSUE TITLE
Pass app version to `CreateCommitment` and `NewMsgPayForBlobs`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/go-square#37]
When creating PFBs, and specifically PFB commitments, we will need to pass the app version to provide enough context for the application to generate the correct commitment for that version.

**Comment by evan-forbes** [comment]
Blocked on authored blobs, as that is the next change that could require this, at least for creating blobTxs, but probably not when we actually call create commitment. We might want to pass the app version anyway to avoid API breaks in the future when we inevitably do need the app version.

**Comment by evan-forbes** [comment]
@cmwaters should we consider this part of authored blobs? if so, can we add this to the tracking for authored blobs?

**Comment by cmwaters** [comment]
> Is this still necessary? [CreateCommitment](https://github.com/celestiaorg/go-square/blob/4135f359b20ddd97b6cb74ecc831f70ffb73f8a5/inclusion/commitment.go#L19) moved to the go-square repo and now accepts a param for `subtreeRootThreshold` which can vary based on app version.

This is correct. `CreateCommitment` can now handle changes to the `subtreeRootThreshold` that was hardcoded before. There is nothing else that is currently hardcoded. I would also refrain from adding app version to the go-square repo. I would prefer if it were agnostic to it and celestia-app would define the parameters but perhaps I could be proven wrong.
