### ISSUE TITLE
This repo shouldn't maintain Merkle tree implemenation

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/go-square#39]
`merkle` pkg contains Merkle tree extracted from Comet/Tendermint. This is a pretty standart RFC compatible Merkle tree implementation that should not be part of this repo. We should consider alternative and likely more efficient implementations out there, as depending on CometBFT is not an option for this repository.

**Comment by rootulp** [comment]
One idea that came up in a synchronous call is we could potentially make the Merkle tree in celestia-core a unique Go package and export it for consumption here so that we can delete the duplicate copy in this repo.

**Comment by cristaloleg** [comment]
This! For a new Celestia member for me it also was not that obvious why we've https://github.com/celestiaorg/smt (which is archived), why we've MT in `go-square` (and partially in `celestia-core`).
